# Site settings
title: UW ChemE 599 Image Analysis for Data Scientists
email: ccurtis7 -- AT -- uw.edu
description: "Image Analysis for Data Scientists"
url: "https://uw-cheme599.github.io/"
twitter_username: derchadmeister
github_username:  uw-cheme599


# Build settings
markdown: kramdown
